### ISSUE TITLE
Extract relevant synchronization data from current GiPHouse database.

### ISSUE THREAD

**Issue by Jer111** [GiPHouse/giphouse-website-spring2023#7]
# One sentence description
Extract the mailing list e-mail and manager from the SQL database and make function that return these variables.

# Suggested implementation
By looking at the already existing function figure out how this could be done, and make the function that extract the data from the database.

**Comment by 1058274** [comment]
- Since in #6 it was decided that for the current sprint it will be *one member account per team*, only the team mailing lists need to be extracted. I am explicitly mentioning this here because the issue's requirements have changed (email addresses of managers not needed anymore).
- Perhaps also useful to see if you can implement selecting certain types of teams (e.g. for a specific course iteration, instead of for all), if you have time left (or just let the admin select them?).

**Comment by Jer111** [comment]
Add if statement to use only current semester
